### PR TITLE
`path.basename` now fails when called with non-string second argument

### PR DESCRIPTION
**Pull request by Almad**

### CODE REVIEW

**Comment by honzajavorek** [comment]
From where the non-string second argument appears? Also, could you please bump the version?

**Comment by Almad** [comment]
[From map's callback signature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).

Shouldn't it be bumped on release instead of with every PR?

**Comment by honzajavorek** [comment]
Thanks. I thought I'd release it right away, but it probably doesn't make much difference now.

**Comment by Almad** [comment]
@honzajavorek then do, I think bump is automated and can be done directly.

I am not sure how you otherwise coordinate multiple PRs :)

**Comment by honzajavorek** [comment]
Ah, I get your point.

**Pull request merged**
